# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8f3a53302fab6105f535cf9d65266b920b97d721ec654579b525735937fa5232dd6c19178683e9d438dec061bfd26660e67321041199bb7f123c704d2ab8117

test:
  secret_key_base: 5587ddbd87910848b468c10ec4bc683e61e46e308de795de829105b7e2ff729c3ed138ec31fd22e25e990917d07127c5e69704700bab9e6a3abcb878e580dca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
